# Copyright (c) 2023-2024 tinyVision.ai Inc.
# SPDX-License-Identifier: Apache-2.0

manifest:
  projects:

    - name: zephyr
      url: https://github.com/tinyvision-ai-inc/zephyr
      revision: pr-usb3-wip
      import:
        name-allowlist:
          - zephyr

    - name: tinyvision_zephyr_sdk
      url: https://github.com/tinyvision-ai-inc/tinyvision_zephyr_sdk
      revision: d66cf6e29c95fb0052d7090b43e5978709e2a04a
