# SPDX-License-Identifier: Apache-2.0

manifest:
  projects:

    - name: zephyr
      url: https://github.com/tinyvision-ai-inc/zephyr
      revision: pr-usb3-uvc
      import:
        name-allowlist:
          - zephyr

    - name: tinyvision_zephyr_sdk
      url: https://github.com/tinyvision-ai-inc/tinyvision_zephyr_sdk
      revision: e1b63c7ab7eb3740863073565bca2abad27dfd91
