# SPDX-License-Identifier: Apache-2.0

manifest:
  projects:

    - name: zephyr
      url: https://github.com/tinyvision-ai-inc/zephyr
      revision: pr-usb3-wip
      import:
        name-allowlist:
          - zephyr

    - name: tinyvision_zephyr_sdk
      url: https://github.com/tinyvision-ai-inc/tinyvision_zephyr_sdk
      revision: 33c83fbd28d8edd38d78cff37bdb1af14e1234b1
