# Copyright (c) 2023-2024 tinyVision.ai Inc.
# SPDX-License-Identifier: Apache-2.0

manifest:
  projects:

    - name: zephyr
      url: https://github.com/tinyvision-ai-inc/zephyr
      revision: feature/video_pix_fmt_y800
      import:
        name-allowlist:
          - zephyr

    - name: tinyvision_zephyr_sdk
      url: https://github.com/tinyvision-ai-inc/priv-modalai
      revision: ba6ef913b21a80da04e4bb957a91a193bc846375
